plc_map = {
    0: {"id_dispositivo": 1, "tipo_senal": 2, "tipo_dato": "bool", "nombre": "MOTOR-1"},
    1: {"id_dispositivo": 2, "tipo_senal": 2, "tipo_dato": "bool", "nombre": "MOTOR-2"},
    2: {"id_dispositivo": 5, "tipo_senal": 2, "tipo_dato": "bool", "nombre": "MOTOR-3"},
    # 3: {"id_dispositivo": 1, "tipo_senal": 2, "tipo_dato": "bool", "nombre": "MOTOR-4"},
    # 4: {"id_dispositivo": 1, "tipo_senal": 2, "tipo_dato": "bool", "nombre": "MOTOR-5"},
    # 5: {"id_dispositivo": 1, "tipo_senal": 2, "tipo_dato": "bool", "nombre": "MOTOR-6"},
    # 6: {"id_dispositivo": 1, "tipo_senal": 2, "tipo_dato": "bool", "nombre": "MOTOR-7"},
    7: {"id_dispositivo": 6, "tipo_senal": 2, "tipo_dato": "bool", "nombre": "F-TERMICA M1"},
    8: {"id_dispositivo": 7, "tipo_senal": 2, "tipo_dato": "bool", "nombre": "F-TERMICA M2"},
    9: {"id_dispositivo": 8, "tipo_senal": 2, "tipo_dato": "bool", "nombre": "F-TERMICA M3"},
    # 10: {"id_dispositivo": 1, "tipo_senal": 2, "tipo_dato": "bool", "nombre": "F-TERMICA M4"},
    # 11: {"id_dispositivo": 1, "tipo_senal": 2, "tipo_dato": "bool", "nombre": "F-TERMICA M5"},
    # 12: {"id_dispositivo": 1, "tipo_senal": 2, "tipo_dato": "bool", "nombre": "F-TERMICA M6"},
    # 13: {"id_dispositivo": 1, "tipo_senal": 2, "tipo_dato": "bool", "nombre": "F-TERMICA M7"},
    14: {"id_dispositivo": 13, "tipo_senal": 2, "tipo_dato": "bool", "nombre": "NIVEL-1"},
    # 15: {"id_dispositivo": 1, "tipo_senal": 2, "tipo_dato": "bool", "nombre": "NIVEL-2"},
    # 16: {"id_dispositivo": 1, "tipo_senal": 2, "tipo_dato": "bool", "nombre": "NIVEL-3"},
    # 17: {"id_dispositivo": 1, "tipo_senal": 2, "tipo_dato": "bool", "nombre": "NIVEL-4"},
    # 18: {"id_dispositivo": 1, "tipo_senal": 2, "tipo_dato": "bool", "nombre": "NIVEL-5"},
    # 19: {"id_dispositivo": 1, "tipo_senal": 2, "tipo_dato": "bool", "nombre": "NIVEL-6"},
    # 20: {"id_dispositivo": 1, "tipo_senal": 2, "tipo_dato": "bool", "nombre": "NIVEL-7"},
    21: {"id_dispositivo": 12, "tipo_senal": 2, "tipo_dato": "bool", "nombre": "PRESOSTATO-1"},
    # 22: {"id_dispositivo": 1, "tipo_senal": 2, "tipo_dato": "bool", "nombre": "PRESOSTATO-2"},
    # 23: {"id_dispositivo": 1, "tipo_senal": 2, "tipo_dato": "bool", "nombre": "PRESOSTATO-3"},
    # 24: {"id_dispositivo": 1, "tipo_senal": 2, "tipo_dato": "bool", "nombre": "PRESOSTATO-4"},
    # 25: {"id_dispositivo": 1, "tipo_senal": 2, "tipo_dato": "bool", "nombre": "PRESOSTATO-5"},
    # 26: {"id_dispositivo": 1, "tipo_senal": 2, "tipo_dato": "bool", "nombre": "PRESOSTATO-6"},
    # 27: {"id_dispositivo": 1, "tipo_senal": 2, "tipo_dato": "bool", "nombre": "PRESOSTATO-7"},
    28: {"id_dispositivo": 9, "tipo_senal": 3, "tipo_dato": "num", "nombre": "TEMPERATURA-M1"},
    29: {"id_dispositivo": 11, "tipo_senal": 3, "tipo_dato": "num", "nombre": "TEMPERATURA-M2"},
    30: {"id_dispositivo": 10, "tipo_senal": 3, "tipo_dato": "num", "nombre": "TEMPERATURA-M3"},
    # 31: {"id_dispositivo": 1, "tipo_senal": 3, "tipo_dato": "bool", "nombre": "TEMPERATURA-M4"},
#     32: {"id_dispositivo": 1, "tipo_senal": 3, "tipo_dato": "bool", "nombre": "TEMPERATURA-M5"},
#     33: {"id_dispositivo": 1, "tipo_senal": 3, "tipo_dato": "bool", "nombre": "TEMPERATURA-M6"},
#     34: {"id_dispositivo": 1, "tipo_senal": 3, "tipo_dato": "bool", "nombre": "TEMPERATURA-M7"}
}
